services:
  jenkins:
    build: ./jenkins
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
